apps:
  - script: "material-collector.js"
    name: "x5process_collect"
    cwd: "./dist/"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_text_indexing"
    cwd: "./dist/"
    args: "-tn uuid.index-material-text -tp ../ontologies/index-material-text"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_text_translation"
    cwd: "./dist/"
    args: "-tn uuid.index-material-text-translate -tp ../ontologies/index-material-text-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_video_translation"
    cwd: "./dist/"
    args: "-tn uuid.index-material-video-translate -tp ../ontologies/index-material-video-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5store_process_material_complete"
    cwd: "./dist/"
    args: "-tn uuid.store-index-complete -tp ../ontologies/store-index-complete"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5store_process_material_incomplete"
    cwd: "./dist/"
    args: "-tn uuid.store-index-incomplete -tp ../ontologies/store-index-incomplete"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"