apps:
  - script: "pipeline.js"
    name: "x5update_material_collect"
    cwd: "./dist/"
    args: "-tn uuid.update-material-select -tp ../topologies/update-material-select"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5update_material_text_translation"
    cwd: "./dist/"
    args: "-tn uuid.update-material-text-translate -tp ../topologies/update-material-text-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5update_material_video_translation"
    cwd: "./dist/"
    args: "-tn uuid.update-material-video-translate -tp ../topologies/update-material-video-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5update_store_material_complete"
    cwd: "./dist/"
    args: "-tn uuid.store-update-complete -tp ../topologies/store-update-complete"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"
