apps:
  - script: "pipeline.js"
    name: "x5store_ua_activity"
    cwd: "./dist/"
    args: "-tn uuid.store-ua-activity -tp ../topologies/store-ua-activity"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5store_recsys_selection"
    cwd: "./dist/"
    args: "-tn uuid.store-recsys-selections -tp ../topologies/store-recsys-selections"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5store_providers"
    cwd: "./dist/"
    args: "-tn uuid.store-providers -tp ../topologies/store-providers"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"